spring:
  profiles:
    active: {set_your_active_profile}
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: {set_port}

dooray:
  token: {set_dooray_token}
  base-url: {base_uri}
  project-id: {your_dooray_project_id}
